export {
  RegisterInputSchema,
  LoginInputSchema,
  RoleEnum,
  RegistrationRoleEnum,
  CounterpartyTypeEnum,
  type RegisterInput,
  type LoginInput,
} from './schemas/auth.js';

export {
  ProfileStep1Schema,
  ProfileStep2Schema,
  ProfileUpdateSchema,
  ConsentAcceptSchema,
  LanguageUpdateSchema,
  GenderEnum,
  LanguageEnum,
  type ProfileStep1,
  type ProfileStep2,
  type ProfileUpdate,
  type ConsentAccept,
  type LanguageUpdate,
} from './schemas/profile.js';

export {
  GoldTypeEnum,
  RecordCreateSchema,
  RecordUpdateSchema,
  RecordSubmitSchema,
  MinerRecordSubmitSchema,
  RecordPhotoUploadSchema,
  type RecordCreate,
  type RecordUpdate,
  type RecordSubmit,
  type MinerRecordSubmit,
  type RecordPhotoUpload,
} from './schemas/record.js';

export {
  PurchaseCreateSchema,
  type PurchaseCreate,
} from './schemas/purchase.js';

export {
  SalesPartnerAddSchema,
  type SalesPartnerAddInput,
} from './schemas/sales-partner.js';

export {
  ComplianceReviewStatusEnum,
  ComplianceReviewCreateSchema,
  type ComplianceReviewCreate,
} from './schemas/compliance.js';

export {
  SurveySubmitSchema,
  SurveyRewardUpdateSchema,
  type SurveySubmitInput,
  type SurveyRewardUpdateInput,
} from './schemas/survey.js';

export {
  type ApiError,
  type MeResponse,
  type UserProfile,
  type ConsentVersionResponse,
  type RecordResponse,
  type RecordPhotoResponse,
  type RecordListItem,
  type RecordListResponse,
  type AvailableRecordListItem,
  type AvailableRecordListResponse,
  type PurchaseResponse,
  type PurchaseListItem,
  type PurchaseListResponse,
  type PurchaseItemResponse,
  type SalesPartnerListItem,
  type SalesPartnerListResponse,
  type AvailablePartnerListItem,
  type AvailablePartnerListResponse,
  type AdminDashboardStats,
  type AdminUserListItem,
  type AdminUserListResponse,
  type AdminUserDetail,
  type AdminRecordListItem,
  type AdminRecordListResponse,
  type AdminRecordDetail,
  type ComplianceReviewResponse,
  type ComplianceReviewListItem,
  type ComplianceReviewListResponse,
  type FeatureFlagsResponse,
  type PaymentSummary,
  type MineSiteResponse,
  type MineSiteListResponse,
  type MetalPurityResponse,
  type RecordReceiptResponse,
  type VisionWeightResult,
  type VisionXrfResult,
  type SurveyDefinitionResponse,
  type SurveyStatusResponse,
  type SurveyListResponse,
  type SurveyAnswerResponse,
  type SurveyResponseDetail,
  type RiskFlagResponse,
  type RiskAssessmentResponse,
  type AdminSurveyStatsResponse,
  type AdminSurveyListResponse,
  type VisionEstimationResult,
  type DocumentResponse,
  type DocumentListResponse,
  type DocumentExtractionResult,
  type EntityPackFile,
  type EntityPackFolder,
  type EntityPackListResponse,
  type EntityPackDownloadResponse,
  type SupplyChainActor,
  type SupplyChainRecord,
  type SupplyChainFlow,
  type SupplyChainMapResponse,
  type TraceabilityStep,
  type TraceabilityPreview,
} from './types/api.js';

export {
  ROLES,
  COUNTERPARTY_TYPES,
  GENDERS,
  LANGUAGES,
  GOLD_TYPES,
  RECORD_STATUSES,
  type Role,
  type CounterpartyType,
  type Gender,
  type Language,
  type GoldType,
  type RecordStatus,
  COMPLIANCE_REVIEW_STATUSES,
  type ComplianceReviewStatus,
  PAYMENT_STATUSES,
  PAYMENT_TYPES,
  PAYMENT_METHODS,
  type PaymentStatus,
  type PaymentType,
  type PaymentMethod,
  METAL_ELEMENTS,
  VISION_CONFIDENCE,
  type MetalElement,
  type VisionConfidence,
  SURVEY_REWARD_STATUSES,
  RISK_LEVELS,
  DOCUMENT_TYPES,
  MANDATORY_DOCUMENT_TYPES,
  type SurveyRewardStatus,
  type RiskLevel,
  type DocumentType,
  type MandatoryDocumentType,
} from './constants.js';

// Phase 7: Survey question definitions & risk rules
export {
  SURVEY_DEFINITIONS,
  getSurveyBySlug,
  getVisibleQuestions,
  type QuestionType,
  type QuestionOption,
  type SurveyQuestionDef,
  type SurveyDef,
} from './surveys/questions.js';

export {
  RISK_FLAGS,
  evaluateRisk,
  type RiskFlagDef,
  type RiskSeverity,
  type TriggeredFlag,
  type RiskLevel as RiskLevelType,
} from './surveys/risk.js';
